import '../models/library_song.dart';
import 'music_library.dart';

/// Sample library used when not running on iOS (e.g. `flutter run -d chrome`
/// on Windows). Generating playlists still calls Claude for real; saving just
/// pretends to.
class DemoMusicLibrary implements MusicLibrary {
  @override
  bool get isDemo => true;

  @override
  Future<MusicAccess> accessStatus() async => MusicAccess.authorized;

  @override
  Future<MusicAccess> requestAccess() async => MusicAccess.authorized;

  @override
  Future<List<LibrarySong>> fetchSongs() async => demoSongs;

  @override
  Future<void> createPlaylist({
    required String name,
    required String description,
    required List<String> songIds,
  }) => Future.delayed(const Duration(milliseconds: 600));
}

final List<LibrarySong> demoSongs = [
  for (final (index, row) in _rows.indexed)
    LibrarySong(
      id: 'demo-$index',
      title: row.$1,
      artist: row.$2,
      album: row.$3,
      genres: [row.$4, 'Music'],
      year: row.$5,
      playCount: row.$6,
      explicit: row.$7,
    ),
];

const _rows = <(String, String, String, String, int, int, bool)>[
  (
    'Paranoid Android',
    'Radiohead',
    'OK Computer',
    'Alternative',
    1997,
    58,
    false,
  ),
  ('No Surprises', 'Radiohead', 'OK Computer', 'Alternative', 1997, 41, false),
  (
    'Weird Fishes/Arpeggi',
    'Radiohead',
    'In Rainbows',
    'Alternative',
    2007,
    73,
    false,
  ),
  ('Reckoner', 'Radiohead', 'In Rainbows', 'Alternative', 2007, 30, false),
  (
    'Midnight City',
    'M83',
    "Hurry Up, We're Dreaming",
    'Electronic',
    2011,
    44,
    false,
  ),
  ('Wait', 'M83', "Hurry Up, We're Dreaming", 'Electronic', 2011, 12, false),
  ('Nightcall', 'Kavinsky', 'OutRun', 'Electronic', 2013, 67, false),
  ('Tech Noir', 'Gunship', 'Gunship', 'Electronic', 2015, 9, false),
  ('Blinding Lights', 'The Weeknd', 'After Hours', 'R&B/Soul', 2020, 88, false),
  ('After Hours', 'The Weeknd', 'After Hours', 'R&B/Soul', 2020, 21, true),
  (
    'Redbone',
    'Childish Gambino',
    'Awaken, My Love!',
    'R&B/Soul',
    2016,
    35,
    true,
  ),
  ('Pink + White', 'Frank Ocean', 'Blonde', 'R&B/Soul', 2016, 52, false),
  ('Nights', 'Frank Ocean', 'Blonde', 'R&B/Soul', 2016, 64, true),
  ('Ivy', 'Frank Ocean', 'Blonde', 'R&B/Soul', 2016, 47, true),
  ('Holocene', 'Bon Iver', 'Bon Iver', 'Alternative', 2011, 39, false),
  (
    'Skinny Love',
    'Bon Iver',
    'For Emma, Forever Ago',
    'Alternative',
    2008,
    26,
    false,
  ),
  (
    'Re: Stacks',
    'Bon Iver',
    'For Emma, Forever Ago',
    'Alternative',
    2008,
    3,
    false,
  ),
  (
    'Pink Moon',
    'Nick Drake',
    'Pink Moon',
    'Singer/Songwriter',
    1972,
    18,
    false,
  ),
  (
    'Northern Sky',
    'Nick Drake',
    'Bryter Layter',
    'Singer/Songwriter',
    1971,
    14,
    false,
  ),
  ('Harvest Moon', 'Neil Young', 'Harvest Moon', 'Rock', 1992, 22, false),
  (
    'Fast Car',
    'Tracy Chapman',
    'Tracy Chapman',
    'Singer/Songwriter',
    1988,
    31,
    false,
  ),
  (
    'Such Great Heights',
    'Iron & Wine',
    'Garden State (Soundtrack)',
    'Folk',
    2004,
    8,
    false,
  ),
  ('Mykonos', 'Fleet Foxes', 'Sun Giant', 'Folk', 2008, 19, false),
  (
    'White Winter Hymnal',
    'Fleet Foxes',
    'Fleet Foxes',
    'Folk',
    2008,
    27,
    false,
  ),
  ('So What', 'Miles Davis', 'Kind of Blue', 'Jazz', 1959, 33, false),
  ('Blue in Green', 'Miles Davis', 'Kind of Blue', 'Jazz', 1959, 29, false),
  (
    'Take Five',
    'The Dave Brubeck Quartet',
    'Time Out',
    'Jazz',
    1959,
    24,
    false,
  ),
  (
    'In a Sentimental Mood',
    'Duke Ellington & John Coltrane',
    'Duke Ellington & John Coltrane',
    'Jazz',
    1963,
    16,
    false,
  ),
  (
    'Gymnopédie No. 1',
    'Erik Satie',
    'Satie: Piano Works',
    'Classical',
    1888,
    11,
    false,
  ),
  (
    'Clair de Lune',
    'Claude Debussy',
    'Debussy: Suite bergamasque',
    'Classical',
    1905,
    15,
    false,
  ),
  ('Mr. Brightside', 'The Killers', 'Hot Fuss', 'Alternative', 2004, 55, false),
  (
    'Seven Nation Army',
    'The White Stripes',
    'Elephant',
    'Alternative',
    2003,
    40,
    false,
  ),
  ('Do I Wanna Know?', 'Arctic Monkeys', 'AM', 'Alternative', 2013, 61, false),
  ('R U Mine?', 'Arctic Monkeys', 'AM', 'Alternative', 2013, 37, false),
  (
    'Everlong',
    'Foo Fighters',
    'The Colour and the Shape',
    'Rock',
    1997,
    48,
    false,
  ),
  ('Smells Like Teen Spirit', 'Nirvana', 'Nevermind', 'Rock', 1991, 42, false),
  ('Back in Black', 'AC/DC', 'Back in Black', 'Rock', 1980, 36, false),
  (
    'Till I Collapse',
    'Eminem',
    'The Eminem Show',
    'Hip-Hop/Rap',
    2002,
    70,
    true,
  ),
  ('HUMBLE.', 'Kendrick Lamar', 'DAMN.', 'Hip-Hop/Rap', 2017, 59, true),
  (
    'Alright',
    'Kendrick Lamar',
    'To Pimp a Butterfly',
    'Hip-Hop/Rap',
    2015,
    34,
    true,
  ),
  (
    'POWER',
    'Kanye West',
    'My Beautiful Dark Twisted Fantasy',
    'Hip-Hop/Rap',
    2010,
    46,
    true,
  ),
  ('Levitating', 'Dua Lipa', 'Future Nostalgia', 'Pop', 2020, 50, false),
  ("Don't Start Now", 'Dua Lipa', 'Future Nostalgia', 'Pop', 2019, 43, false),
  ('As It Was', 'Harry Styles', "Harry's House", 'Pop', 2022, 38, false),
  ('Dancing On My Own', 'Robyn', 'Body Talk', 'Pop', 2010, 57, false),
  (
    'Get Lucky',
    'Daft Punk',
    'Random Access Memories',
    'Electronic',
    2013,
    45,
    false,
  ),
  ('One More Time', 'Daft Punk', 'Discovery', 'Electronic', 2001, 39, false),
  (
    'Strobe',
    'deadmau5',
    'For Lack of a Better Name',
    'Electronic',
    2009,
    25,
    false,
  ),
  ('Teardrop', 'Massive Attack', 'Mezzanine', 'Electronic', 1998, 32, false),
  ('Glory Box', 'Portishead', 'Dummy', 'Electronic', 1994, 20, false),
  ('Dreams', 'Fleetwood Mac', 'Rumours', 'Rock', 1977, 62, false),
  ('Go Your Own Way', 'Fleetwood Mac', 'Rumours', 'Rock', 1977, 28, false),
  ('Heroes', 'David Bowie', '"Heroes"', 'Rock', 1977, 23, false),
  (
    'September',
    'Earth, Wind & Fire',
    'The Best of Earth, Wind & Fire, Vol. 1',
    'R&B/Soul',
    1978,
    30,
    false,
  ),
  (
    'Superstition',
    'Stevie Wonder',
    'Talking Book',
    'R&B/Soul',
    1972,
    27,
    false,
  ),
  (
    "Ain't No Mountain High Enough",
    'Marvin Gaye & Tammi Terrell',
    'United',
    'R&B/Soul',
    1967,
    17,
    false,
  ),
  ('Harvest', 'Neil Young', 'Harvest', 'Rock', 1972, 0, false),
  (
    'Lua',
    'Bright Eyes',
    "I'm Wide Awake, It's Morning",
    'Singer/Songwriter',
    2005,
    0,
    false,
  ),
  (
    'Motion Sickness',
    'Phoebe Bridgers',
    'Stranger in the Alps',
    'Alternative',
    2017,
    13,
    false,
  ),
  ('Kyoto', 'Phoebe Bridgers', 'Punisher', 'Alternative', 2020, 10, true),
];
